### ISSUE TITLE
Be not correct

### ISSUE THREAD

**Issue by stefandevo** [cedvdb/phone_form_field#1] opened 2021-04-21 19:37 UTC
Tested the demo page with +32 4544452145544525455 and it says that it is valid...

**Comment by cedvdb** [comment] 2021-04-22 09:23
I'm fixing this today, I found the root cause of it, I'm adding more tests as well

**Comment by cedvdb** [comment] 2021-04-22 22:59
Fixed in 1.0.1

**Closed by cedvdb** 2021-04-22 22:59 UTC
