### ISSUE TITLE
Expose autofillHints

### ISSUE THREAD

**Issue by xvrh** [cedvdb/phone_form_field#8] opened 2021-08-20 10:11 UTC
Currently, the library exposes a flag `withHint` and inject `AutofillHints.telephoneNumberNational` if true.
On iOS, I doesn't seem to work. I need to specify `AutofillHints.telephoneNumber` instead.

Can we simply expose the whole `Iterable<String>? autofillHints` instead of the bool flag?

**Comment by cedvdb** [comment] 2021-08-20 12:50
I don't have an apple phone nor a mac. The problem is that there is two "inputs". One for the dial code and one for the national number (the telephone number without the dial code).

My worries with this are two fold:
  - the fact that `AutofillHints.telephoneNumber` does not work on ios seem to be a bug on flutter itself and not this library
  - exposing the autofill hints would make people perplex as they would use `AutofillHints.telephoneNumber` which is not really the autofill hint expected. The one expected is the national number.
  
  
However this is an easy feature to add.

**Comment by xvrh** [comment] 2021-08-20 12:57
Would it be possible that the field detect that it is filled (or pasted) with an international prefix and automatically change the national code?
ie. In if I paste "+32477123456" into the PhoneField, I expect it will change the national field.

**Comment by cedvdb** [comment] 2021-08-20 12:59
Well the phone number parser library allows to parse a phone number in its entirety. So parsing a full phone number and extracting the two parts is possible. What I'm not sure about is if it's possible to hi-jack the process of autofill hint in a non-hacky way,

**Comment by xvrh** [comment] 2021-08-20 13:32
I imagine that the AutoFill feature can't be 100% correct all the time. I imagine it works by looking at data entered in other apps with annotated textfield.

I think the best thing to do are: 
- Have the field detect that it is filled with an international phone and update the dropdown automatically.
- Let the user specify it's own list of AutofillHints.

**Comment by cedvdb** [comment] 2021-08-21 00:35
This seems to be the best course of action although that will make one breaking change: 

  - phone_numbers_parser library exposes two parsers, a light and an heavy one.
  - phone_form_field lets the user decide which one to use via the param `bool lightParser`
  
The issue is that the light parser cannot parse a phone number without the country code (because multiple countries share the same dial code). 

Therefor I'll have to remove the possibility to use the light parser with this feature. I guess something functional is preferable though.

**Comment by cedvdb** [comment] 2021-08-21 00:53
This will be done with a breaking change:

 - The possibility to use the light parser will be removed and only the bigger phone parser from the phone_numbers_parser library will be used, as its the only one that can parse phone numbers without country code. It was introduced recently in this library via the param `bool lightParser` however it seems to me that this is an essential feature, more essential than the possibility to chose a parser.

**Comment by cedvdb** [comment] 2021-08-23 18:33
Can you try the latest :

```dart
dependencies:
  phone_form_field:
    git:
      url: https://github.com/cedvdb/phone_form_field
```

**Comment by xvrh** [comment] 2021-08-24 08:36
Hi @cedvdb,
I tried the latest version, thanks a lot!

AutofillHints is not exposed directly so it is good for me.

There is still one thing I would like: when I fill with an international phone number, it should update the country code. I think internally we should try a parsing with `PhoneNumber().parseRaw()` first and check if the isoCode is the same or not.

**Comment by cedvdb** [comment] 2021-08-24 09:34
> when I fill with an international phone number, it should update the country code

Hum if you copy paste an international phone number or auto fill it should update the country code

**Comment by xvrh** [comment] 2021-08-24 09:55
> it is now AutofillHints.telephoneNumber. It is also exposed in BasePhoneFormField but that requires some manual setups

Sorry the "not" in my sentence was a typo :-(

> Hum if you copy paste an international phone number or auto fill it should update the country code. Doesn't that work for you ?

Yes I don't see this behaviour. 
When I create a `PhoneFormField` with default values. When I focus, it chooses "+1" (us) by default. Now I paste "+32477124578". The country code stays "+1" and it displays "invalid phone number"

**Comment by cedvdb** [comment] 2021-08-24 09:59
> Now I paste "+32477124578". The country code stays "+1" and it displays "invalid phone number"

What device are you on ? it works for me here https://cedvdb.github.io/phone_form_field/#/

**Comment by xvrh** [comment] 2021-08-24 10:17
This is with an iPhone (real and simulator). I seems the prefix "+" is lost somewhere before it is pasted.

Indeed it work well in the web page.

**Comment by cedvdb** [comment] 2021-09-20 17:38
Should be fixed in next release

https://github.com/cedvdb/phone_form_field/pull/32

**Closed by cedvdb** 2021-09-20 17:38 UTC
