### ISSUE TITLE
Country flag not showing when unfocus

### ISSUE THREAD

**Issue by moinkhan780** [cedvdb/phone_form_field#84] opened 2022-01-11 15:43 UTC
Country flag needs to be show properly when user focus or unfocus the textfield

When focused 
<img width="309" alt="Screen Shot 2022-01-11 at 8 42 30 PM" src="https://user-images.githubusercontent.com/88693191/148974193-f64e7e7e-873f-41ee-a49d-bc24c0cce23c.png">

When unfocused 
<img width="309" alt="Screen Shot 2022-01-11 at 8 42 40 PM" src="https://user-images.githubusercontent.com/88693191/148974206-ab0bd92c-5b47-4c3f-9f9f-be4ff384b837.png">

**Comment by cedvdb** [comment] 2022-01-11 18:49
duplicate of https://github.com/cedvdb/phone_form_field/issues/61

This is an issue with flutter, there is no way to have the flag aligned if it is shown.

This is the flutter issue. It is not moving currently so some activity from people would be nice so it moves a bit:

https://github.com/flutter/flutter/issues/91174

**Comment by cedvdb** [comment] 2022-02-18 10:25
Please try this branch https://github.com/cedvdb/phone_form_field/tree/fixing_unfocus_icon

**Comment by Gabrielhn** [comment] 2022-02-18 14:01
Test video of the tests from the mentioned branch in:

 https://github.com/cedvdb/phone_form_field/issues/85#issuecomment-1044568451

**Closed** 2022-02-18 15:40 UTC
